snowflake:
  account: !env_var SNOWFLAKE_ACCOUNT
  user: !env_var SNOWFLAKE_USER
  password: !env_var SNOWFLAKE_PASSWORD
  role: !env_var SNOWFLAKE_ROLE
  warehouse: !env_var SNOWFLAKE_WAREHOUSE

procedures:
  development:
    - name: create_temp_database
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: owner
      args:
        - name: database_name
          type: varchar
        - name: ttl
          type: varchar
          default: 14
      returns: varchar
      comment: |
        Allows the caller to make a temporary development database that cleans up after a designated amount of time.

  admin:
    - name: create_database_reader
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: caller
      args:
        - name: database_name
          type: varchar
      returns: varchar
      comment: |
        Creates a role with full read access to the provided database with name of the form <DATABASE_NAME>_READER

    - name: create_database_writer
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: caller
      args:
        - name: database_name
          type: varchar
      returns: varchar
      comment: |
        Creates a role with full write access to the provided database with name of the form <DATABASE_NAME>_WRITER

    - name: drop_database_if_expired
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: owner
      args:
        - name: database_name
          type: varchar
        - name: drop_timestamp
          type: varchar
      returns: varchar
      comment: |
        Drops the given database if the database ttl has expired