snowflake:
  account: !env_var SNOWFLAKE_ACCOUNT
  user: !env_var SNOWFLAKE_USER
  password: !env_var SNOWFLAKE_PASSWORD
  role: !env_var SNOWFLAKE_ROLE
  warehouse: !env_var SNOWFLAKE_WAREHOUSE

procedures:
  development:
    - name: create_temp_database
      replace_if_exists: true
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: caller
      args:
        database_name: varchar
        ttl: varchar
      returns: varchar
      comment: |
        Allows the caller to make a temporary development
        database that cleans up after a designated amount of time.

  admin:
    - name: create_database_reader
      replace_if_exists: true
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: owner
      args:
        database_name: varchar
      returns: varchar
      comment: |
        Creates a role with full read access to the provided database with name of the form <DATABASE_NAME>_READER

    - name: create_database_writer
      replace_if_exists: true
      database: !env_var SNOWFLAKE_DATABASE
      schema: !env_var SNOWFLAKE_SCHEMA
      language: javascript
      execute_as: owner
      args:
        database_name: varchar
      returns: varchar
      comment: |
        Creates a role with full write access to the provided database with name of the form <DATABASE_NAME>_WRITER